[package]
name = "darwin_lib"
version = "0.1.0"
authors = ["Louis de Wardt <contact@louis.dewardt.uk>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "simulate"
harness = false
